### ISSUE TITLE
[Bug] bypass button, is supposed to work ?

### ISSUE THREAD

**Issue by Daniele71** [vvvar/PeakEater#62] opened 2023-02-15 18:14 UTC
Hello, plugin from Proaudio repo on openSUSE tw, on Ardour 7.2 the bypass button inside the plugin windows does nothing when clicked. It becomes green when I bypass the plugin with the host bypassa button. It should work or it's just an indicator ?

Another small issue is that if a move the mouse cursor over the plugin, it flow faster while the cursor is moving. 
Xorg with Amd rx 550. Let me know if you want more info and/or a specific bureport.
Thanks.

**Comment by vvvar** [comment] 2023-03-12 20:17
Hello. Reworked Bypass button as part of [this feature](https://github.com/vvvar/PeakEater/pull/59). Ideally, Bypass shall work independently of host's, but i haven't checked that with Ardour, maybe it is somehow different in this host. Thanks, will try it out after new feature.
Haven't noticed performance issue with Ableton 10 on macOS(my main DAW where i'm testing). Will check with Ardour once this feature will be released(since there are performance optimisations).

**Comment by Daniele71** [comment] 2023-03-20 23:29
> Checked latest release with Ardour 7.3.0 on macOS 12.6.3. Turned out, Ardour actually synchronises plugin's Bypass button with Host's Bypass button. So it shall properly bypass signal no matter Host or Plugin's Bypass used(they shall be in sync). Also haven't noticed any visible performance issues. Please check out latest release and let me know if you have issues https://github.com/vvvar/PeakEater/releases/tag/v0.6.0

The vst3 version is working now but the lv2 still the same. Version 0.6.1 with ardour-7.3
Thanks.

**Comment by leochras** [comment] 2023-03-21 06:13
Can confirm (also 0.6.1, Ardour 7.3) , didn't check the VST3 before. Also, I seem to get better UI performance (faster refresh, no lag) with VST3 but not with LV2..

**Comment by edogawa23** [comment] 2023-03-21 11:27
I also can confirm nonworking bypass switch via Ardour 7.3 or jalv.select. Using VST3 in A7.3, it works.

**Comment by leochras** [comment] 2023-03-21 11:45
I also tried reaper v6.78 with the LV2 and bypass also doesn't work

**Comment by vvvar** [comment] 2023-03-26 10:59
Was able to reproduce on macOS 12.6.3 using v0.6.1 LV2 with Reaper v6.73. Seems LV2 handles bypass somehow differently. Will take a look. Until it fixed - please stick to either VST3 or CLAP. Thanks.

**Comment by vvvar** [comment] 2023-07-01 19:38
Hey everyone.
Unified bypass across all plugin formats. Now it is independent from the host's button.
Available from [v0.6.5](https://github.com/vvvar/PeakEater/releases/tag/v0.6.5). If you're using macOS then please use [v0.7.1](https://github.com/vvvar/PeakEater/releases/tag/v0.7.1) since CLAP and LV2 were broken for macOS in 0.6.5

**Comment by derkrasseleo** [comment] 2023-07-02 18:52
I can confirm a working bypass button with the latest LV2 in Ardour.

**Comment by vvvar** [comment] 2023-07-03 06:43
Great, thanks for the quick checking!

**Closed by vvvar** 2023-07-03 06:43 UTC
Labels: Bug
